name: Train Inception V4

on:
  push: 
    branches:
      [train, inceptionv4]

jobs:
  
  train:
    runs-on: ubuntu-latest
    container: 
      image: nclgbd/mltraindev:develop
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Setup env
      shell: bash -l {0}
      run: bash scripts/build.sh
      
    - name: Train model
      id: train_inceptionv4
      shell: bash -l {0}
      run: |
        mkdir -p media/ incorrect_images/ saved_models/ artifacts/
        ls -a
        conda activate torch_base
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        python -m pytorch_vision_utils.train --model_name "inceptionv4" --parameters_path "parameters.json" --debug "False"
    # Moving artifacts
    - name: Move artifacts
      run: |
        mv media artifacts/
        mv saved_models/inceptionv4.pth artifacts/
        mv incorrect_images/ artifacts
    # Save artifacts
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: inceptionv4_${{ steps.train_inceptionv4.outputs.sha_short }}
        path: artifacts/
